cmake_minimum_required(VERSION 3.24)
project(opheap-workspace)

option(OPHEAP_BUILD_TESTS "Build opheap tests" ON)
option(OPHEAP_BUILD_BENCHMARKS "Build opheap benchmarks" OFF)
option(OPHEAP_BUILD_EXAMPLES "Build opheap examples" ON)
option(OPHEAP_BUILD_APPLICATIONS "Build opheap-cli and opheap-browser" ON)
option(OPHEAP_ENABLE_SANITIZERS "Enable ASan and UBSan" OFF)

add_subdirectory(libraries/libopheap-core)
add_subdirectory(libraries/libopheap-sql)
add_subdirectory(libraries/libopheap-cli)

if(OPHEAP_BUILD_APPLICATIONS)
    add_subdirectory(applications/opheap-cli)
    add_subdirectory(applications/opheap-browser)
    add_subdirectory(applications/opheap-sql)
endif()
if(OPHEAP_BUILD_TESTS)
    enable_testing()
    add_subdirectory(tests)
endif()
if(OPHEAP_BUILD_BENCHMARKS)
    add_subdirectory(benchmarks)
endif()
if(OPHEAP_BUILD_EXAMPLES)
    add_subdirectory(examples)
endif()
